import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ru' | 'uz';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        // Navigation
        dashboard: "Dashboard",
        glucose: "Glucose",
        symptoms: "Symptoms",
        calculator: "Calculator",
        wellness: "Wellness",
        medical_lab: "Medical Lab",
        settings: "Settings",
        logout: "Logout",
        sos: "SOS Emergency",

        // Settings & Profile
        account_calibration: "Account Calibration",
        system_identity: "System Identity",
        biographic_data: "Biographic Data",
        biographic_desc: "Update your clinical identity and avatar",
        profile_metadata: "Profile Metadata",
        display_name: "Display Name",
        email_address: "Email Address",
        commit_changes: "Commit Changes",
        synchronizing: "Synchronizing...",
        sync_success: "Profile configuration synchronized successfully.",
        emergency_protocol: "Emergency Protocol",
        medical_id: "Emergency Medical ID",
        diabetes_type: "Diabetes Type",
        diabetes_type_label: "Diabetes Type",
        blood_group: "Blood Group",
        blood_group_label: "Blood Group",
        emergency_contact: "Emergency Contact",
        save_sos: "Save SOS Medical ID",
        save_medical_id: "Save SOS Medical ID",
        medical_id_updated: "Emergency Medical ID updated and primed for SOS.",
        critical_notes: "Critical Notes",
        instructions_placeholder: "Any medications or instructions for first responders...",
        system_aesthetics: "System Aesthetics",
        interface_protocols: "Interface Protocols",
        light_pulse: "Light Pulse",
        midnight: "Midnight",
        adaptive: "Adaptive",
        language_selection: "Language Preference",
        unit_selection: "Glucose Units",
        medical_alerts: "Medical Alerts",
        notifications_active: "Notifications Active",
        enable_notifications: "Enable Notifications",
        credential_reset: "Credential Reset",
        dispatch_reset_desc: "Dispatch a secured password reset link to your email.",
        reset_password_btn: "Reset Password",
        token_reset_dispatched: "Security token reset link dispatched to your inbox.",
        system_health: "System Health",
        real_time_status: "Real-time status of your metabolic interface",
        verified_clinical: "Verified Clinical",
        aes_protocol: "AES-256 Protocol",
        adherence_alert: "Adherence Alert",
        protocol_monitored: "Your active medical protocols are being monitored by the system's neural clock.",
        protocol_inactive: "Protocol alerts currently inactive. Enabling reminders improves metabolic long-term success.",
        bio_link_active: "Bio-Link Active",

        // Dashboard
        health_overview: "Health Overview",
        system_synopsis: "System Synopsis",
        latest_glucose: "Latest Glucose",
        metabolic_projection: "Metabolic Projection",
        scheduled_protocol: "Scheduled Protocol",
        carb_intake: "Carb Intake",
        ai_intelligence: "AI Intelligence",
        ai_prediction: "AI Prediction",
        next_60_min: "Next 60 Minutes",
        projected_level: "Projected Level",
        rate_of_change: "Rate of Change",
        urgent_action: "Urgent Action",
        glucose_trends: "Glucose Trends",
        activity: "Activity",
        dispatch_report: "Dispatch Report",
        personalized_analytics: "Personalized health analytics and real-time biometric synchronization.",
        next_check: "Next Check",
        no_scheduled_alerts: "No Scheduled Alerts",
        monitoring_disengaged: "Monitoring Disengaged",
        daily_cumulative: "Daily cumulative",
        latest_updates: "Latest Updates",
        silent_system: "Silent System",
        patterns_visual: "Visualizing biological patterns over time",
        hb_optimal: "Optimal",
        hb_pre: "Pre-diabetic",
        hb_diabetic: "Diabetic Range",

        // Prediction Engine
        equilibrum: "Metabolic equilibrium achieved.",
        stability: "Biometric stability detected.",
        approaching_threshold: "Biological trend approaching threshold.",
        proactive_carb: "Consider a proactive fast-acting carb intake (15g).",
        rapid_drop: "Rapid downward trajectory detected.",
        clinical_action: "Immediate clinical action advised. Verify with fingerstick.",
        elevated_projection: "Elevated glycemic projection detected.",
        verify_iob: "Verify insulin active (IOB) and hydration levels.",
        awaiting_calibration: "Awaiting biological calibration...",
        add_readings: "Add more readings for AI predictive insights.",
        ai_suggestion: "Predictive engine suggests checking IOB or consuming glucose based on velocity.",

        // Symptom Tracker
        symptom_analysis: "Symptom Analysis",
        how_feeling: "How are you feeling?",
        select_observations: "Select current observations",
        custom_symptom_prompt: "Enter symptom name:",
        other: "Other",
        overall_severity: "Overall Severity",
        intensity_index: "Intensity Index",
        mild: "Mild",
        normal: "Normal",
        moderate: "Moderate",
        strong: "Strong",
        severe: "Severe",
        processing: "Processing...",
        finalize_symptom: "Finalize Symptom Log",
        feeling_cycle: "Feeling Cycle",
        temporal_archive: "Temporal Archive",
        no_biometric_shifts: "No Biometric Shifts",
        daily_wellbeing_history: "Your daily wellbeing history will consolidate here.",
        intensity: "Intensity",
        correlation_board: "Correlation Board",
        metric_pattern_analysis: "Metric-Symptom Pattern Analysis",
        biological_insight: "Biological Insight",
        neurological_fatigue_insight: "Biometric trends indicate a strong correlation between glucose elevations and neurological fatigue.",
        deep_analysis_view: "Deep Analysis View",
        fatigue: "Fatigue",
        dizziness: "Dizziness",
        thirst: "Excessive Thirst",
        vision: "Blurred Vision",
        sweating: "Sweating",
        irritability: "Irritability",
        sleep_disturbance: "Sleep Disturbance",

        // Insulin Calculator
        insulin_precision: "Insulin Precision",
        dosage_calc: "Dosage Calculation",
        accurate_dose_prediction: "Accurate dose prediction based on glycemic load and physiological targets.",
        algorithmic_base: "Algorithmic Base",
        dosage_board: "Dosage Board",
        calc_optimal_units: "Calculate optimal insulin units",
        total_xe: "Total Bread Units (XE)",
        current_glucose: "Current Glucose",
        suggested_dose: "Suggested Dose",
        units: "Units",
        archiving: "Archiving...",
        sync_meal_journal: "Sync to Meal Journal",
        calibration_factors: "Calibration Factors",
        xe_standardization: "XE Standardization",
        standard: "Standard",
        correction_factor: "Correction Factor",
        meal_journal: "Meal Journal",
        logs_count: "Logs",
        journal_empty: "Journal Empty",
        start_logging_meals: "Start logging your meals to track your insulin patterns.",
        carbs_g: "g Carbs",
        expert_tip: "Expert Tip",
        accuracy_matters_tip: "Accuracy matters. Using consistent XE ratios helps stabilize post-meal glucose spikes and reduces hypoglycemic risks.",

        // Wellness
        wellness_vitals: "Wellness & Vitals",
        vital_systems: "Vital Systems",
        holistic_overview: "A holistic overview of your physical health markers, synchronized for a balanced lifestyle.",
        daily_ledger: "Daily Ledger",
        health_checkin: "Health Check-in",
        update_vitals_projection: "Update your vitals to maintain accurate health projections.",
        body_weight: "Body Weight",
        rest_duration: "Rest Duration",
        hydration_level: "Hydration Level",
        kilograms: "kg",
        hours: "hrs",
        liters: "liters",
        sync_health_profile: "Synchronizing Health Profile...",
        finalize_daily_entry: "Finalize Daily Entry",
        medical_focus: "Medical Focus",
        sleep_optimizes_tip: "Sleep optimizes glucose metabolism by up to 40%.",
        scientific_tip: "Scientific Tip",
        hydration_tip: "Consistent hydration prevents rapid cortisol spikes.",
        vitals_archive: "Vitals Archive",
        historical_performance: "Historical Performance",
        no_data_synced: "No Data Synced",
        begin_journey_logging: "Begin your journey by logging today's markers.",

        // Metabolic Lab
        clinical_insights: "Advanced Clinical Insights",
        clinical_deep_dive: "Correlative deep-dives into your biological metadata for precise therapy adjustment.",
        clinical_stability: "Clinical Stability",
        tir_low: "Low (< 4.0)",
        tir_in_range: "In Range (4.0-8.5)",
        tir_high: "High (> 8.5)",
        target_met: "Target Met",
        tir_gold_standard: "Primary metric for metabolic control quality",
        trigger_analysis: "Trigger Analysis",
        post_prandial_desc: "Post-prandial glycemic response correlation",
        post_meal_glucose: "Post-Meal Glucose",
        carb_load_g: "Carb Load (g)",
        awaiting_cross_analysis: "Awaiting Cross-Analysis Data",
        meal_glucose_data_req: "Requires meal logs followed by glucose checks within 2 hours.",
        subjective_distribution: "Subjective distribution",
        symptom_frequency: "Symptom Frequency",
        top_biological_triggers: "Top biological triggers detected across your therapeutic journey.",

        // SOS & Auth
        metabolic_unity: "Metabolic Unity",
        harmonizing_desc: "Harmonizing biological data with intuitive technology for clinical-grade metabolic control.",
        encryption_level: "Encryption Level",
        biometric_vault: "Biometric Vault Protocols",
        analytical_depth: "Analytical Depth",
        glycemic_insight: "Real-time Glycemic Insight",
        system_access: "System Access",
        initialize: "Initialize",
        register: "Register",
        auth_credentials: "Authenticating metabolic credentials",
        create_profile: "Creating high-fidelity patient profile",
        full_name: "Full Name",
        access_password: "Access Password",
        forgot_token: "Forgot Token?",
        gain_access: "Gain Access",
        establish_profile: "Establish Profile",
        social_interface: "Social Interface",
        new_to_system: "New to the system?",
        return_to_protocol: "Return to protocol?",
        open_account: "Open Account",
        identify_status: "Identify Status",
        emergency_id: "Emergency Medical ID",
        responder_instructions: "Vital instructions for first responders",
        condition: "Condition",
        recent_glycemic_data: "Recent Glycemic Data",
        therapeutic_notes: "Therapeutic Notes",
        acknowledge_return: "Acknowledge & Return",
        default_notes: "Patient may require rapid-acting glucose or insulin depending on state. Check sensor for continuous monitoring."
    },
    ru: {
        // Navigation
        dashboard: "Панель",
        glucose: "Глюкоза",
        symptoms: "Симптомы",
        calculator: "Калькулятор",
        wellness: "Велнес",
        medical_lab: "Мед Лаборатория",
        settings: "Настройки",
        logout: "Выйти",
        sos: "SOS Экстренно",

        // Settings & Profile
        account_calibration: "Калибровка Аккаунта",
        system_identity: "Идентичность Системы",
        biographic_data: "Биографические данные",
        biographic_desc: "Обновите свою клиническую идентичность и аватар",
        profile_metadata: "Метаданные профиля",
        display_name: "Отображаемое имя",
        email_address: "Электронная почта",
        commit_changes: "Применить изменения",
        synchronizing: "Синхронизация...",
        sync_success: "Конфигурация профиля успешно синхронизирована.",
        emergency_protocol: "Протокол экстренной помощи",
        medical_id: "Медицинский ID SOS",
        diabetes_type: "Тип Диабета",
        diabetes_type_label: "Тип диабета",
        blood_group: "Группа Крови",
        blood_group_label: "Группа Крови",
        emergency_contact: "Контакт для Экстренной Связи",
        save_sos: "Сохранить SOS ID",
        save_medical_id: "Сохранить SOS Мед ID",
        medical_id_updated: "Экстренный медицинский ID обновлен и готов к SOS.",
        critical_notes: "Критические заметки",
        instructions_placeholder: "Любые лекарства или инструкции для спасателей...",
        system_aesthetics: "Эстетика системы",
        interface_protocols: "Протоколы интерфейса",
        light_pulse: "Светлый пульс",
        midnight: "Полночь",
        adaptive: "Адаптивный",
        language_selection: "Выбор языка",
        unit_selection: "Единицы Глюкозы",
        medical_alerts: "Медицинские оповещения",
        notifications_active: "Уведомления активны",
        enable_notifications: "Включить уведомления",
        credential_reset: "Сброс учетных данных",
        dispatch_reset_desc: "Отправить защищенную ссылку для сброса пароля на вашу почту.",
        reset_password_btn: "Сбросить пароль",
        token_reset_dispatched: "Ссылка для сброса токена безопасности отправлена на ваш почтовый ящик.",
        system_health: "Здоровье системы",
        real_time_status: "Статус вашего метаболического интерфейса в реальном времени",
        verified_clinical: "Верифицировано Клинически",
        aes_protocol: "Протокол AES-256",
        adherence_alert: "Оповещение о приверженности",
        protocol_monitored: "Ваши активные медицинские протоколы отслеживаются нейронными часами системы.",
        protocol_inactive: "Оповещения протокола в данный момент неактивны. Включение напоминаний улучшает долгосрочный успех.",
        bio_link_active: "Биосвязь активна",

        // Dashboard
        health_overview: "Обзор Здоровья",
        system_synopsis: "Синопсис Системы",
        latest_glucose: "Последняя Глюкоза",
        metabolic_projection: "Метаболический Прогноз",
        scheduled_protocol: "Запланированный Протокол",
        carb_intake: "Прием Углеводов",
        ai_intelligence: "Интеллект ИИ",
        ai_prediction: "Прогноз ИИ",
        next_60_min: "Следующие 60 минут",
        projected_level: "Прогнозируемый Уровень",
        rate_of_change: "Скорость Изменения",
        urgent_action: "Срочное Действие",
        glucose_trends: "Тренды Глюкозы",
        activity: "Активность",
        dispatch_report: "Отправить Отчет",
        personalized_analytics: "Персонализированная аналитика здоровья и синхронизация биометрии в реальном времени.",
        next_check: "След. Проверка",
        no_scheduled_alerts: "Нет запланированных оповещений",
        monitoring_disengaged: "Мониторинг отключен",
        daily_cumulative: "Накопительно за день",
        latest_updates: "Последние обновления",
        silent_system: "Система в режиме ожидания",
        patterns_visual: "Визуализация биологических паттернов во времени",
        hb_optimal: "Оптимально",
        hb_pre: "Преддиабет",
        hb_diabetic: "Диабетический диапазон",

        // Prediction Engine
        equilibrum: "Метаболическое равновесие достигнуто.",
        stability: "Обнаружена биометрическая стабильность.",
        approaching_threshold: "Биологический тренд приближается к порогу.",
        proactive_carb: "Рассмотрите возможность приема быстрых углеводов (15 г).",
        rapid_drop: "Обнаружена траектория быстрого снижения.",
        clinical_action: "Рекомендуется немедленное клиническое действие. Проверьте глюкометром.",
        elevated_projection: "Обнаружен повышенный гликемический прогноз.",
        verify_iob: "Проверьте активный инсулин (IOB) и уровень гидратации.",
        awaiting_calibration: "Ожидание биологической калибровки...",
        add_readings: "Добавьте больше данных для прогнозов ИИ.",
        ai_suggestion: "Прогностический движок предлагает проверить IOB или употребить глюкозу на основе скорости изменения.",

        // Symptom Tracker
        symptom_analysis: "Анализ Симптомов",
        how_feeling: "Как вы себя чувствуете?",
        select_observations: "Выберите текущие наблюдения",
        custom_symptom_prompt: "Введите название симптома:",
        other: "Другое",
        overall_severity: "Общая Тяжесть",
        intensity_index: "Индекс Интенсивности",
        mild: "Легкий",
        normal: "Нормальный",
        moderate: "Умеренный",
        strong: "Сильный",
        severe: "Тяжелый",
        processing: "Обработка...",
        finalize_symptom: "Завершить Журнал Симптомов",
        feeling_cycle: "Цикл Самочувствия",
        temporal_archive: "Временной Архив",
        no_biometric_shifts: "Нет Биометрических Сдвигов",
        daily_wellbeing_history: "Ваша ежедневная история благополучия будет собрана здесь.",
        intensity: "Интенсивность",
        correlation_board: "Доска Корреляции",
        metric_pattern_analysis: "Анализ Паттернов Метрик и Симптомов",
        biological_insight: "Биологическое Озарение",
        neurological_fatigue_insight: "Биометрические тренды указывают на сильную корреляцию между повышением уровня глюза и неврологической усталостью.",
        deep_analysis_view: "Вид Глубокого Анализа",
        fatigue: "Усталость",
        dizziness: "Головокружение",
        thirst: "Сильная Жажда",
        vision: "Размытое Зрение",
        sweating: "Потливость",
        irritability: "Раздражительность",
        sleep_disturbance: "Нарушение Сна",

        // Insulin Calculator
        insulin_precision: "Инсулиновая Точность",
        dosage_calc: "Расчет Дозировки",
        accurate_dose_prediction: "Точный прогноз дозы на основе гликемической нагрузки и физиологических целей.",
        algorithmic_base: "Алгоритмическая База",
        dosage_board: "Доска Дозировок",
        calc_optimal_units: "Рассчитать оптимальные единицы инсулина",
        total_xe: "Всего Хлебных Единиц (ХЕ)",
        current_glucose: "Текущая Глюкоза",
        suggested_dose: "Рекомендуемая Доза",
        units: "Ед",
        archiving: "Архивация...",
        sync_meal_journal: "Синхронизировать с Журналом Питания",
        calibration_factors: "Факторы Калибровки",
        xe_standardization: "Стандартизация ХЕ",
        standard: "Стандарт",
        correction_factor: "Фактор Коррекции",
        meal_journal: "Журнал Питания",
        logs_count: "Записей",
        journal_empty: "Журнал Пуст",
        start_logging_meals: "Начните записывать приемы пищи, чтобы отслеживать паттерны инсулина.",
        carbs_g: "г Углеводов",
        expert_tip: "Совет Эксперта",
        accuracy_matters_tip: "Точность важна. Использование стабильных коэффициентов ХЕ помогает стабилизировать скачки глюкозы после еды и снижает риски гипогликемии.",

        // Wellness
        wellness_vitals: "Велнес и Виталы",
        vital_systems: "Жизненные Системы",
        holistic_overview: "Целостный обзор ваших физических показателей здоровья, синхронизированный для сбалансированного образа жизни.",
        daily_ledger: "Ежедневный Реестр",
        health_checkin: "Проверка Здоровья",
        update_vitals_projection: "Обновите свои виталы для поддержания точных прогнозов здоровья.",
        body_weight: "Вес Тела",
        rest_duration: "Длительность Отдыха",
        hydration_level: "Уровень Гидратации",
        kilograms: "кг",
        hours: "ч",
        liters: "л",
        sync_health_profile: "Синхронизация Профиля Здоровья...",
        finalize_daily_entry: "Завершить Ежедневную Запись",
        medical_focus: "Медицинский Фокус",
        sleep_optimizes_tip: "Сон оптимизирует метаболизм глюкозы до 40%.",
        scientific_tip: "Научный Совет",
        hydration_tip: "Постоянное увлажнение предотвращает резкие скачки кортизола.",
        vitals_archive: "Архив Виталов",
        historical_performance: "Историческая Производительность",
        no_data_synced: "Данные не Синхронизированы",
        begin_journey_logging: "Начните свой путь, записывая сегодняшние показатели.",

        // Metabolic Lab
        clinical_insights: "Продвинутые Клинические Инсайты",
        clinical_deep_dive: "Корреляционные погружения в ваши биологические метаданные для точной корректировки терапии.",
        clinical_stability: "Клиническая Стабильность",
        tir_low: "Низкий (< 4.0)",
        tir_in_range: "В Норме (4.0-8.5)",
        tir_high: "Высокий (> 8.5)",
        target_met: "Цель Достигнута",
        tir_gold_standard: "Основная метрика качества метаболического контроля",
        trigger_analysis: "Анализ Триггеров",
        post_prandial_desc: "Корреляция постпрандиального гликемического ответа",
        post_meal_glucose: "Глюкоза После Еды",
        carb_load_g: "Углеводная Нагрузка (г)",
        awaiting_cross_analysis: "Ожидание Данных Кросс-Анализа",
        meal_glucose_data_req: "Требуются записи о еде, сопровождаемые проверкой глюкозы в течение 2 часов.",
        subjective_distribution: "Субъективное распределение",
        symptom_frequency: "Частота Симптомов",
        top_biological_triggers: "Лучшие биологические триггеры, обнаруженные за время вашего лечения.",

        // SOS & Auth
        metabolic_unity: "Метаболическое Единство",
        harmonizing_desc: "Гармонизация биоданных с интуитивными технологиями для клинического контроля метаболизма.",
        encryption_level: "Уровень Шифрования",
        biometric_vault: "Протоколы Биометрического Хранилища",
        analytical_depth: "Глубина Аналитики",
        glycemic_insight: "Инсайт Гликемии в Реальном Времени",
        system_access: "Доступ к Системе",
        initialize: "Инициализация",
        register: "Регистрация",
        auth_credentials: "Аутентификация учетных данных",
        create_profile: "Создание высокоточного профиля пациента",
        full_name: "Полное Имя",
        access_password: "Пароль Доступа",
        forgot_token: "Забыли Токен?",
        gain_access: "Получить Доступ",
        establish_profile: "Создать Профиль",
        social_interface: "Социальный Интерфейс",
        new_to_system: "Впервые в системе?",
        return_to_protocol: "Вернуться к протоколу?",
        open_account: "Открыть Аккаунт",
        identify_status: "Идентифицировать Статус",
        emergency_id: "Экстренный Мед ID",
        responder_instructions: "Важные инструкции для спасателей",
        condition: "Состояние",
        recent_glycemic_data: "Последние Данные Гликемии",
        therapeutic_notes: "Терапевтические Заметки",
        acknowledge_return: "Принять и Вернуться",
        default_notes: "Пациенту может потребоваться глюкоза быстрого действия или инсулин в зависимости от состояния. Проверьте сенсор."
    },
    uz: {
        // Navigation
        dashboard: "Boshqaruv paneli",
        glucose: "Glyukoza",
        symptoms: "Simptomlar",
        calculator: "Kalkulyator",
        wellness: "Salomatlik",
        medical_lab: "Tibbiy laboratoriya",
        settings: "Sozlamalar",
        logout: "Chiqish",
        sos: "SOS Favqulodda holat",

        // Settings & Profile
        account_calibration: "Hisobni kalibrlash",
        system_identity: "Tizim identifikatsiyasi",
        biographic_data: "Biografik ma'lumotlar",
        biographic_desc: "Klinik identifikatsiyangizni va avataringizni yangilang",
        profile_metadata: "Profil metama'lumotlari",
        display_name: "Ko'rsatiladigan ism",
        email_address: "Elektron pochta",
        commit_changes: "O'zgarishlarni saqlash",
        synchronizing: "Sinxronizatsiya qilinmoqda...",
        sync_success: "Profil konfiguratsiyasi muvaffaqiyatli sinxronlashtirildi.",
        emergency_protocol: "Favqulodda protokol",
        medical_id: "Favqulodda tibbiy ID",
        diabetes_type: "Diabet turi",
        diabetes_type_label: "Diabet turi",
        blood_group: "Qon guruhi",
        blood_group_label: "Qon guruhi",
        emergency_contact: "Favqulodda bog'lanish",
        save_sos: "SOS IDni saqlash",
        save_medical_id: "SOS tibbiy IDni saqlash",
        medical_id_updated: "Favqulodda tibbiy ID yangilandi va SOSga tayyorlandi.",
        critical_notes: "Kritik eslatmalar",
        instructions_placeholder: "Qutqaruvchilar uchun har qanday dori yoki ko'rsatmalar...",
        system_aesthetics: "Tizim estetikasi",
        interface_protocols: "Interfeys protokollari",
        light_pulse: "Yorug'lik pulsi",
        midnight: "Yarim tun",
        adaptive: "Adaptiv",
        language_selection: "Tilni tanlash",
        unit_selection: "Glyukoza birliklari",
        medical_alerts: "Tibbiy ogohlantirishlar",
        notifications_active: "Bildirishnomalar faol",
        enable_notifications: "Bildirishnomalarni yoqish",
        credential_reset: "Hisob ma'lumotlarini tiklash",
        dispatch_reset_desc: "Xavfsiz parolni tiklash havolasini elektron pochtangizga yuborish.",
        reset_password_btn: "Parolni tiklash",
        token_reset_dispatched: "Xavfsizlik tokenini tiklash havolasi pochta qutingizga yuborildi.",
        system_health: "Tizim holati",
        real_time_status: "Metabolik interfeysingizning real vaqtdagi holati",
        verified_clinical: "Klinik jihatdan tasdiqlangan",
        aes_protocol: "AES-256 protokoli",
        adherence_alert: "Rivojlanish ogohlantirishi",
        protocol_monitored: "Sizning faol tibbiy protokollaringiz tizimning neyron soatlari tomonidan kuzatilmoqda.",
        protocol_inactive: "Protokol ogohlantirishlari hozirda faol emas. Eslatmalarni yoqish metabolik muvaffaqiyatni yaxshilaydi.",
        bio_link_active: "Bio-havola faol",

        // Dashboard
        health_overview: "Salomatlik sharhi",
        system_synopsis: "Tizim sinopsisi",
        latest_glucose: "Oxirgi glyukoza",
        metabolic_projection: "Metabolik prognoz",
        scheduled_protocol: "Rejalashtirilgan protokol",
        carb_intake: "Uglevod iste'moli",
        ai_intelligence: "AI intellekti",
        ai_prediction: "AI prognozi",
        next_60_min: "Keyingi 60 daqiqa",
        projected_level: "Prognoz qilingan daraja",
        rate_of_change: "O'zgarish tezligi",
        urgent_action: "Shoshilinch harakat",
        glucose_trends: "Glyukoza tendentsiyalari",
        activity: "Faoliyat",
        dispatch_report: "Hisobotni yuborish",
        personalized_analytics: "Shaxsiylashtirilgan sog'liqni saqlash tahlili va real vaqtdagi biometrik sinxronizatsiya.",
        next_check: "Keyingi tekshiruv",
        no_scheduled_alerts: "Rejalashtirilgan bildirishnomalar yo'q",
        monitoring_disengaged: "Monitoring o'chirilgan",
        daily_cumulative: "Kunlik jami",
        latest_updates: "Oxirgi yangilanishlar",
        silent_system: "Tizim kutish rejimida",
        patterns_visual: "Vaqt o'tishi bilan biologik naqshlarni vizuallashtirish",
        hb_optimal: "Optimal",
        hb_pre: "Prediabet",
        hb_diabetic: "Diabetik diapazon",

        // Prediction Engine
        equilibrum: "Metabolik muvozanatga erishildi.",
        stability: "Biometrik barqarorlik aniqlandi.",
        approaching_threshold: "Biologik tendentsiya chegaraga yaqinlashmoqda.",
        proactive_carb: "Tez ta'sir qiluvchi uglevodlarni (15 g) qabul qilishni ko'rib chiqing.",
        rapid_drop: "Tez pasayish traektoriyasi aniqlandi.",
        clinical_action: "Darhol klinik harakat qilish tavsiya etiladi. Glyukometr bilan tekshiring.",
        elevated_projection: "Yuqori glikemik prognoz aniqlandi.",
        verify_iob: "Faol insulin (IOB) va gidratatsiya darajasini tekshiring.",
        awaiting_calibration: "Biologik kalibrlash kutilmoqda...",
        add_readings: "AI bashoratlari uchun ko'proq ma'lumot qo'shing.",
        ai_suggestion: "Bashoratli dvigatel tezlikka asoslanib IOBni tekshirishni yoki glyukoza iste'mol qilishni taklif qiladi.",

        // Symptom Tracker
        symptom_analysis: "Simptomlar tahlili",
        how_feeling: "O'zingizni qanday his qilyapsiz?",
        select_observations: "Hozirgi kuzatuvlarni tanlang",
        custom_symptom_prompt: "Simptom nomini kiriting:",
        other: "Boshqa",
        overall_severity: "Umumiy og'irlik",
        intensity_index: "Intensivlik indeksi",
        mild: "Yengil",
        normal: "Normal",
        moderate: "O'rtacha",
        strong: "Kuchli",
        severe: "Og'ir",
        processing: "Ishlov berilmoqda...",
        finalize_symptom: "Simptomlar jurnalini yakunlash",
        feeling_cycle: "Hissiyot tsikli",
        temporal_archive: "Vaqtinchalik arxiv",
        no_biometric_shifts: "Biometrik o'zgarishlar yo'q",
        daily_wellbeing_history: "Kundalik salomatlik tarixingiz shu yerda jamlanadi.",
        intensity: "Intensivlik",
        correlation_board: "Korrelyatsiya kengashi",
        metric_pattern_analysis: "Metrik-simptom naqshlari tahlili",
        biological_insight: "Biologik tushuncha",
        neurological_fatigue_insight: "Biometrik tendentsiyalar glyukoza ko'tarilishi va nevrologik charchoq o'rtasida kuchli korrelyatsiya mavjudligini ko'rsatavi.",
        deep_analysis_view: "Chuqur tahlil ko'rinishi",
        fatigue: "Charchoq",
        dizziness: "Bosh aylanishi",
        thirst: "Haddan tashqari tashnalik",
        vision: "Xira ko'rish",
        sweating: "Terlash",
        irritability: "Asabiylashish",
        sleep_disturbance: "Uyqu buzilishi",

        // Insulin Calculator
        insulin_precision: "Insulin aniqligi",
        dosage_calc: "Dozani hisoblash",
        accurate_dose_prediction: "Glikemik yuk va fiziologik maqsadlarga asoslangan dozani aniq bashorat qilish.",
        algorithmic_base: "Algoritmik baza",
        dosage_board: "Doza paneli",
        calc_optimal_units: "Optimal insulin birliklarini hisoblang",
        total_xe: "Jami non birliklari (XE)",
        current_glucose: "Hozirgi glyukoza",
        suggested_dose: "Tavsiya etilgan doza",
        units: "Birl.",
        archiving: "Arxivlanmoqda...",
        sync_meal_journal: "Ovqatlanish jurnaliga sinxronlash",
        calibration_factors: "Kalibrlash omillari",
        xe_standardization: "XE standartlashtirish",
        standard: "Standart",
        correction_factor: "Tuzatish koeffitsienti",
        meal_journal: "Ovqatlanish jurnali",
        logs_count: "Yozuvlar",
        journal_empty: "Jurnal bo'sh",
        start_logging_meals: "Insulin naqshlarini kuzatish uchun ovqatlaringizni yozishni boshlang.",
        carbs_g: "g uglevodlar",
        expert_tip: "Ekspert maslahati",
        accuracy_matters_tip: "Aniqlik muhimdir. Izchil XE nisbatlaridan foydalanish ovqatdan keyingi glyukoza ko'tarilishini barqarorlashtirishga yordam beradi va gipoglikemiya xavfini kamaytiradi.",

        // Wellness
        wellness_vitals: "Salomatlik va vitallar",
        vital_systems: "Hayotiy tizimlar",
        holistic_overview: "Muvozanatli hayot tarzi uchun sinxronlashtirilgan jismoniy salomatlik ko'rsatkichlarining yaxlit sharhi.",
        daily_ledger: "Kundalik daftar",
        health_checkin: "Salomatlikni tekshirish",
        update_vitals_projection: "Aniq salomatlik prognozlarini saqlash uchun vitallaringizni yangilang.",
        body_weight: "Tana vazni",
        rest_duration: "Dam olish muddati",
        hydration_level: "Gidratatsiya darajasi",
        kilograms: "kg",
        hours: "soat",
        liters: "litr",
        sync_health_profile: "Salomatlik profilini sinxronlash...",
        finalize_daily_entry: "Kundalik yozuvni yakunlash",
        medical_focus: "Tibbiy diqqat markazi",
        sleep_optimizes_tip: "Uyqu glyukoza almashinuvini 40% gacha optimallashtiradi.",
        scientific_tip: "Ilmiy maslahat",
        hydration_tip: "Doimiy gidratatsiya kortizolning keskin ko'tarilishini oldini oladi.",
        vitals_archive: "Vitallar arxiv",
        historical_performance: "Tarixiy samaradorlik",
        no_data_synced: "Ma'lumotlar sinxronlanmagan",
        begin_journey_logging: "Bugungi ko'rsatkichlarni yozib, sayohatingizni boshlang.",

        // Metabolic Lab
        clinical_insights: "Ilg'or klinik tushunchalar",
        clinical_deep_dive: "Terapiyani aniq sozlash uchun biologik metama'lumotlaringizga korrelyatsion chuqur kirish.",
        clinical_stability: "Klinik barqarorlik",
        tir_low: "Past (< 4.0)",
        tir_in_range: "Me'yorda (4.0-8.5)",
        tir_high: "Yuqori (> 8.5)",
        target_met: "Maqsadga erishildi",
        tir_gold_standard: "Metabolik nazorat sifatining asosiy ko'rsatkichi",
        trigger_analysis: "Trigger tahlili",
        post_prandial_desc: "Ovqatdan keyingi glikemik javob korrelyatsiyasi",
        post_meal_glucose: "Ovqatdan keyingi glyukoza",
        carb_load_g: "Uglevod yuki (g)",
        awaiting_cross_analysis: "Kross-tahlil ma'lumotlari kutilmoqda",
        meal_glucose_data_req: "Ovqatlanishdan keyin 2 soat ichida glyukoza tekshiruvi talab qilinadi.",
        subjective_distribution: "Sub'ektiv taqsimot",
        symptom_frequency: "Simptomlar chastotasi",
        top_biological_triggers: "Davolanish davomida aniqlangan asosiy biologik triggerlar.",

        // SOS & Auth
        metabolic_unity: "Metabolik birlik",
        harmonizing_desc: "Klinik darajadagi metabolik nazorat uchun biologik ma'lumotlarni intuitiv texnologiya bilan uyg'unlashtirish.",
        encryption_level: "Shifrlash darajasi",
        biometric_vault: "Biometrik ombor protokollari",
        analytical_depth: "Tahliliy chuqurlik",
        glycemic_insight: "Haqiqiy vaqtdagi glikemik tushuncha",
        system_access: "Tizimga kirish",
        initialize: "Ishga tushirish",
        register: "Ro'yxatdan o'tish",
        auth_credentials: "Metabolik ma'lumotlarni autentifikatsiya qilish",
        create_profile: "Yuqori sifatli bemor profilini yaratish",
        full_name: "To'liq ism",
        access_password: "Kirish paroli",
        forgot_token: "Tokenni unutdingizmi?",
        gain_access: "Kirish",
        establish_profile: "Profil yaratish",
        social_interface: "Ijtimoiy interfeys",
        new_to_system: "Tizimda yangimisiz?",
        return_to_protocol: "Protokolga qaytish?",
        open_account: "Hisob ochish",
        identify_status: "Holatni aniqlash",
        emergency_id: "Favqulodda tibbiy ID",
        responder_instructions: "Qutqaruvchilar uchun muhim ko'rsatmalar",
        condition: "Holat",
        blood_group_label: "Qon guruhi",
        recent_glycemic_data: "Oxirgi glikemik ma'lumotlar",
        therapeutic_notes: "Terapevtik eslatmalar",
        acknowledge_return: "Tasdiqlash va qaytish",
        default_notes: "Bemor holatiga qarab tez ta'sir qiluvchi glyukoza yoki insulinga muhtoj bo'lishi mumkin. Sensorni tekshiring."
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(
        (localStorage.getItem('diabetes-lang') as Language) || 'en'
    );

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('diabetes-lang', lang);
    };

    const t = (key: string) => {
        return (translations[language] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};
